商品購入機能
sasaotomofumi/furima31990 pull request #6
Opened 2020-11-21 10:30 UTC by sasaotomofumi

＃what
商品購入機能の実装。
order、addressテーブルの作成。商品購入フォームの作成。API導入。クレカ決済導入。

#why 
商品購入機能の実装の為。

単体テスト
https://gyazo.com/3b0b733494b1c9ec5230cc468df90042

2020-11-21 10:37 UTC, yutakatahira reviewed
レビュー依頼ありがとうございます！
コメントしましたので、ご確認をお願いいたします！

2020-11-21 10:37 UTC, yutakatahira commented on app/controllers/orders_controller.rb
> +      @product = Product.find(params[:product_id])
6,17行目に記述されている```@product = Product.find(params[:product_id])```は記述が同一ファイル内で重複していますので、private以下にメソッドを定義しbefore_actionで呼び出しましょう！

2020-11-21 10:37 UTC, yutakatahira commented on spec/factories/order_shipping_addresses.rb
> +    phone_number { '09012345678' }
建物の記述を行いましょう！
そして建物が空でも購入できることのテストを行いましょう！

2020-11-21 10:37 UTC, yutakatahira commented on spec/models/order_shipping_address_spec.rb
> +    it 'phone_numberに-を含めると商品購入することができないこと' do
電話番号が12桁以上だと保存できないことのテストも行いましょう！

2020-11-21 10:40 UTC, yutakatahira commented
テストコードのキャプチャ画像ありがとうございます！
以下のキャプチャ画像もいただけますと幸いです。
お手数おかけいたしますが、よろしくお願いいたします。

```
- 購入に成功する動画
- 購入に失敗してエラーが表示させる動画
- ログアウト状態のユーザーが商品購入ページに遷移しようとすると、ログインページに遷移する動画
- ログイン状態の出品者が、URLを直接入力して自身の出品した商品購入ページに遷移しようとすると、トップページに遷移する動画
- ログアウト状態のユーザーは、URLを直接入力して商品購入ページに遷移しようとすると、商品の販売状況に関わらずログインページに遷移する動画
- ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品購入ページへ遷移しようとすると、トップページに遷移する動画
```

2020-11-22 00:05 UTC, sasaotomofumi commented
＃what
商品購入機能の実装。
単体テスト電話番号１２桁以上はと購入できないこと。factores building_name空で追加。
app/controllers/orders_controller.rb　同じコードbefore_actionに定義。
sould out表示切り替え

#why
商品購入機能の実装の為。

単体テスト
https://gyazo.com/e51b3eec6b8f6b27c5e034aeeea521f7
商品購入成功
https://gyazo.com/d1d7a00f89bb959a4200b7aa6c8f892d
商品購入失敗
https://gyazo.com/259a662c430efafbfbdefe90dacb5d30
ログアウト状態のユーザーが商品購入ページに遷移しようとすると、ログインページに遷移
https://gyazo.com/8c9815d3aac67d98e99118bea96df032
ログイン状態の出品者が、URLを直接入力して自身の出品した商品購入ページに遷移しようとすると、トップページに遷移
https://gyazo.com/169657642abba872c53cd802926ea4a1
ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品購入ページへ遷移しようとすると、トップページに遷移
https://gyazo.com/d21e707a84c12ade7eba1ad94caa3adb
ログアウト状態のユーザーは、URLを直接入力して商品購入ページに遷移しようとすると、商品の販売状況に関わらずログインページに遷移
https://gyazo.com/eb9ea9e22f310b071e6a57cbfcb24aa1

2020-11-22 01:49 UTC, i-date reviewed
修正とキャプチャ動画ありがとうございます！
追加コメントいたしましたので、ご確認をお願いいたします。

2020-11-22 01:49 UTC, i-date commented on spec/factories/order_shipping_addresses.rb
> +    building_name { '' }
7行目のbuilding_nameには、値は空ではなくて何かしらの値を用意しましょう。
ダミーデータでは全ての値が入力されている状態にしておくため。

2020-11-22 01:49 UTC, i-date commented on spec/models/order_shipping_address_spec.rb
> +    end
建物名は任意入力になりますので、「建物名は空でも購入できる」というテストを追加しましょう。

2020-11-22 01:57 UTC, sasaotomofumi commented
＃what
商品購入機能の実装。
factores building_nameダミーデータ追加。
単体テストbilding_name空でも保存追加

#why
商品購入機能保証の為。

単体テスト
https://gyazo.com/ec6b41d29a27813387b696de690adc22

2020-11-22 02:14 UTC, kei2223 requested changes
レビューのご依頼いただきありがとうございます。

修正点確認させていただきました。
追加で１点コメントさせていただきましたので、ご確認のほどよろしくお願いいたします。

2020-11-22 02:14 UTC, kei2223 commented on app/javascript/card.js
> +  Payjp.setPublicKey("pk_test_3781376578919d5950caddfc");
payjpのキーに関しては、環境変数に定義して、
そこから呼び出すような仕組みにされているので、直接書かれている分の記述は削除しておきましょう。

2020-11-22 02:20 UTC, sasaotomofumi commented
＃what
商品購入機能の実装。
pay.jp。キー名が直接書かれている記述削除

#why
商品購入時、セキリュティ機能の保証の為。

2020-11-22 02:23 UTC, kei2223 reviewed
レビューのご依頼いただきありがとうございます。

修正点確認させていただきました。

こちらLGTMとさせていただきます！
実装お疲れさまでした！

2020-11-22 02:25 UTC, merged